name: Update learner table

on: push

jobs:
  run:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set-up R
      uses: r-lib/actions/setup-r@master
      with:
        r-version: release
        Ncpus: 4

    - name: "[Stage] Prepare"
      run: |
        Rscript -e "if (!requireNamespace('remotes')) install.packages('remotes', type = 'source')"
        Rscript -e "if (getRversion() < '3.2' && !requireNamespace('curl')) install.packages('curl', type = 'source')"

    - name: "[Stage] Install"
      if: matrix.config.os != 'macOS-latest' || matrix.config.r != 'devel'
      run: Rscript -e "remotes::install_github('ropensci/tic')" -e "print(tic::dsl_load())" -e "tic::prepare_all_stages()" -e "tic::before_install()" -e "tic::install()"

    - name: Update table
      run: Rscript build_learner_table.R

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
