on:
  push:
    branches: master
    paths: '**/C50**'
  pull_request:
    branches: master
    paths: '**/C50**'
  schedule:
    - cron: "0 4 * * *"

name: C50 (ubuntu-latest, release)

jobs:
  all:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.env.TEST }} Test

    strategy:
      matrix:
        env:
          - { test: "Learner"}
          - { test: "Param"}
        config:
          - { os: ubuntu-latest, r: "release" }       

    env:
      PKG: C50
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RGL_USE_NULL: true
      TEST: ${{ matrix.env.test }}
      
    steps:
      - uses: actions/checkout@v2.2.0

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          Ncpus: 4

      - uses: r-lib/actions/setup-tinytex@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: "[Stage] Prepare & Install"
        run: |
          Rscript -e "install.packages('remotes', type = 'source')" -e "remotes::install_github('ropensci/tic')" -e "print(tic::dsl_load())" -e "tic::prepare_all_stages()" -e "tic::before_install()" -e "tic::install()"

      - name: "[Stage] Script"
        run: |
          R CMD INSTALL .
          Rscript -e "tic::script()"

      - name: "[Stage] Upload R CMD check artifacts"
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-r${{ matrix.env.PKG }}-results
          path: check
